[package]
name = "annual"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_bits = { path = "bevy_bits" }
paste = "1.0.15"
rand = "0.8.5"
winnow = "0.6.20"

[dependencies.bevy]
version = "0.14.1"
features = ["dynamic_linking", "wav", "mp3"]

[dependencies.pulldown-cmark]
version = "0.12.2"
default-features = false
features = ["simd"]

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 0

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[profile.dev.package."bevy_bits"]
opt-level = 0
