[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
bevy_bits = { path = "../bevy_bits", features = ["proc-macro"] }
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = "2.0.89"
